### ISSUE TITLE
Old java version is not available

### ISSUE THREAD

**Issue by SecLoop** [righettod/log-requests-to-sqlite#15]
java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.kke.a(Unknown Source)
	at burp.kke.<init>(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.gc.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

![image](https://user-images.githubusercontent.com/15940596/84472510-dcb50700-acb9-11ea-9f5a-ab671108c7d1.png)

log-requests-to-sqlite Old java version is not supported ???

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

![image](https://user-images.githubusercontent.com/15940596/84472593-0706c480-acba-11ea-83ab-240776b817dd.png)

**Comment by SecLoop** [comment]
LogRequestsToSQLite version 1.0.9

**Comment by righettod** [comment]
Hi,

I have aligned the version of Java with the one used by Burp (last version), so, I use Java 11 for the developpement.

Burp come with Java 13 (jre):

![image](https://user-images.githubusercontent.com/1573775/84474145-a744f500-ac8a-11ea-96ef-a034cec1d7b8.png)

If you have installed the extension from the store, then, the jar of the extension is build by the Burp team.

In all case Java >= 11 is needed to run the extension.

Hope this help.

**Comment by SecLoop** [comment]
Thank you very much.But I really want to allow it on burp 1.7
I'll also consider a new version of burp
